package swagger

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// GenerateReport creates a comprehensive Markdown report and JSON data file
// from the fuzzing results.
func GenerateReport(report *FuzzReport, outputDir string) error {
	cleanOutputDir := filepath.Clean(outputDir)
	if err := os.MkdirAll(cleanOutputDir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// 1. Generate Markdown report
	mdPath := filepath.Join(cleanOutputDir, "api_fuzz_report.md")
	if err := generateMarkdownReport(report, mdPath); err != nil {
		return fmt.Errorf("failed to generate markdown report: %w", err)
	}

	// 2. Export anomalies as JSON for programmatic analysis
	if len(report.Anomalies) > 0 {
		jsonPath := filepath.Join(cleanOutputDir, "api_fuzz_anomalies.json")
		if err := exportJSON(report.Anomalies, jsonPath); err != nil {
			return fmt.Errorf("failed to export anomalies JSON: %w", err)
		}
	}

	// 3. Export full results as JSON
	jsonPath := filepath.Join(cleanOutputDir, "api_fuzz_full_results.json")
	if err := exportJSON(report, jsonPath); err != nil {
		return fmt.Errorf("failed to export full results JSON: %w", err)
	}

	return nil
}

func generateMarkdownReport(report *FuzzReport, path string) error {
	cleanPath := filepath.Clean(path)
	f, err := os.Create(cleanPath)
	if err != nil {
		return err
	}
	defer f.Close()

	w := func(format string, args ...interface{}) {
		fmt.Fprintf(f, format, args...)
	}

	// Header
	w("# 🔒 API Security Fuzzing Report\n\n")
	w("**Generated:** `%s`\n\n", time.Now().Format("2006-01-02 15:04:05"))
	w("---\n\n")

	// Executive Summary
	w("## 📊 Executive Summary\n\n")
	w("| Metric | Value |\n")
	w("|--------|-------|\n")
	w("| **Spec Source** | `%s` |\n", report.SpecURL)
	w("| **Target Base URL** | `%s` |\n", report.BaseURL)
	w("| **Endpoints Discovered** | `%d` |\n", report.TotalEndpoints)
	w("| **Total Fuzz Requests** | `%d` |\n", report.TotalRequests)
	w("| **Total Anomalies** | `%d` |\n", report.TotalAnomalies)
	w("| **Duration** | `%.1f seconds` |\n", report.DurationSeconds)
	w("\n")

	// Severity Breakdown
	w("### Severity Breakdown\n\n")
	w("| Severity | Count |\n")
	w("|----------|-------|\n")
	w("| 🔴 CRITICAL | `%d` |\n", report.CriticalCount)
	w("| 🟠 HIGH | `%d` |\n", report.HighCount)
	w("| 🟡 MEDIUM | `%d` |\n", report.MediumCount)
	w("\n")

	// Risk verdict
	if report.CriticalCount > 0 {
		w("> ⛔ **CRITICAL vulnerabilities detected.** Immediate remediation required.\n\n")
	} else if report.HighCount > 0 {
		w("> ⚠️ **HIGH severity issues detected.** Review and remediate before production.\n\n")
	} else if report.TotalAnomalies > 0 {
		w("> ℹ️ **Minor anomalies detected.** Review recommended but not blocking.\n\n")
	} else {
		w("> ✅ **No anomalies detected.** API appears resilient to fuzzing attacks.\n\n")
	}

	w("---\n\n")

	// Endpoints Discovered
	w("## 📋 Endpoints Discovered (%d)\n\n", report.TotalEndpoints)
	w("| # | Method | Path | Operation | Parameters |\n")
	w("|---|--------|------|-----------|------------|\n")
	for i, ep := range report.Endpoints {
		paramCount := len(ep.Params) + len(ep.BodyFields)
		w("| %d | `%s` | `%s` | %s | %d |\n", i+1, ep.Method, ep.Path, ep.OperationID, paramCount)
	}
	w("\n")

	// Detailed Anomalies
	if len(report.Anomalies) > 0 {
		w("---\n\n")
		w("## 🚨 Anomalies Detected (%d)\n\n", len(report.Anomalies))

		// Group anomalies by severity
		criticals := filterBySeverity(report.Anomalies, "CRITICAL")
		highs := filterBySeverity(report.Anomalies, "HIGH")
		mediums := filterBySeverity(report.Anomalies, "MEDIUM")

		if len(criticals) > 0 {
			w("### 🔴 CRITICAL (%d)\n\n", len(criticals))
			writeAnomalyTable(f, criticals)
		}

		if len(highs) > 0 {
			w("### 🟠 HIGH (%d)\n\n", len(highs))
			writeAnomalyTable(f, highs)
		}

		if len(mediums) > 0 {
			w("### 🟡 MEDIUM (%d)\n\n", len(mediums))
			writeAnomalyTable(f, mediums)
		}
	}

	// Footer
	w("---\n\n")
	w("*Generated by Web QA Automation — Swagger/OpenAPI Fuzzing Engine*\n")

	return nil
}

func writeAnomalyTable(f *os.File, anomalies []FuzzResult) {
	w := func(format string, args ...interface{}) {
		fmt.Fprintf(f, format, args...)
	}

	w("| # | Method | Endpoint | Field | Category | Status | Description |\n")
	w("|---|--------|----------|-------|----------|--------|-------------|\n")

	limit := len(anomalies)
	if limit > 50 {
		limit = 50
	}

	for i, a := range anomalies[:limit] {
		endpoint := a.Endpoint
		if len(endpoint) > 60 {
			endpoint = endpoint[:60] + "..."
		}
		desc := strings.ReplaceAll(a.Description, "|", "\\|")
		w("| %d | `%s` | `%s` | `%s` | %s | `%d` | %s |\n",
			i+1, a.Method, endpoint, a.FieldName, a.Category, a.StatusCode, desc)
	}

	if len(anomalies) > 50 {
		w("\n*... and %d more anomalies. See `api_fuzz_anomalies.json` for the full list.*\n\n", len(anomalies)-50)
	}

	w("\n")
}

func filterBySeverity(results []FuzzResult, severity string) []FuzzResult {
	var filtered []FuzzResult
	for _, r := range results {
		if r.Severity == severity {
			filtered = append(filtered, r)
		}
	}
	return filtered
}

func exportJSON(data interface{}, path string) error {
	jsonData, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return err
	}
	cleanPath := filepath.Clean(path)
	return os.WriteFile(cleanPath, jsonData, 0644)
}
