package loadtester

import (
	"bytes"
	"fmt"
	"math/rand"
	"net/http"
	"os"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

type LoadResult struct {
	TotalRequests int64
	SuccessCount  int64
	ErrorCount    int64
	TotalTime     time.Duration
	MinLatency    time.Duration
	MaxLatency    time.Duration
	AvgLatency    time.Duration
}

func createRequest(method, targetURL, currentBody string) (*http.Request, error) {
	var req *http.Request
	var err error

	if currentBody != "" {
		req, err = http.NewRequest(method, targetURL, bytes.NewBuffer([]byte(currentBody)))
		if req != nil {
			req.Header.Set("Content-Type", "application/json")
		}
	} else {
		req, err = http.NewRequest(method, targetURL, nil)
	}
	return req, err
}

func executeWorkerRequest(client *http.Client, method, targetURL, currentBody string) (time.Duration, bool, bool) {
	req, err := createRequest(method, targetURL, currentBody)
	if err != nil {
		return 0, false, false
	}

	reqStart := time.Now()
	resp, err := client.Do(req)
	latency := time.Since(reqStart)

	if resp != nil && resp.Body != nil {
		resp.Body.Close()
	}

	isSuccess := err == nil && resp != nil && resp.StatusCode < 400
	return latency, isSuccess, true
}

func RunLoadTest(targetURL string, users int, duration time.Duration, method string, bodyJson string) LoadResult {
	var wg sync.WaitGroup
	var totalReq, successReq, errReq int64

	bufferSize := users * 1000
	if bufferSize > 1000000 {
		bufferSize = 1000000
	}
	latencyCh := make(chan time.Duration, bufferSize)

	stopCh := make(chan struct{})
	go func() {
		time.Sleep(duration)
		close(stopCh)
	}()

	start := time.Now()
	rand.Seed(time.Now().UnixNano())

	customTransport := &http.Transport{
		MaxIdleConns:        0,
		MaxIdleConnsPerHost: users * 2,
		MaxConnsPerHost:     0,
		IdleConnTimeout:     30 * time.Second,
		DisableKeepAlives:   false,
	}

	client := &http.Client{
		Transport: customTransport,
		Timeout:   10 * time.Second,
	}

	for i := 0; i < users; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			for {
				select {
				case <-stopCh:
					return
				default:
					currentBody := bodyJson
					if currentBody != "" && strings.Contains(currentBody, "{{RANDOM}}") {
						randomVal := fmt.Sprintf("%d", rand.Intn(9999999))
						currentBody = strings.ReplaceAll(currentBody, "{{RANDOM}}", randomVal)
					}

					latency, isSuccess, reqCreated := executeWorkerRequest(client, method, targetURL, currentBody)
					if !reqCreated {
						atomic.AddInt64(&errReq, 1)
						continue
					}

					atomic.AddInt64(&totalReq, 1)

					if !isSuccess {
						atomic.AddInt64(&errReq, 1)
					} else {
						atomic.AddInt64(&successReq, 1)
					}

					select {
					case latencyCh <- latency:
					default:
					}
				}
			}
		}()
	}

	wg.Wait()
	close(latencyCh)
	totalTime := time.Since(start)

	var minLatency time.Duration = 999 * time.Hour
	var maxLatency time.Duration = 0
	var totalLatency time.Duration = 0
	var recordedCount int64 = 0

	for l := range latencyCh {
		if l < minLatency {
			minLatency = l
		}
		if l > maxLatency {
			maxLatency = l
		}
		totalLatency += l
		recordedCount++
	}

	var avgLatency time.Duration
	if recordedCount > 0 {
		avgLatency = time.Duration(int64(totalLatency) / recordedCount)
	} else {
		minLatency = 0
	}

	return LoadResult{
		TotalRequests: totalReq,
		SuccessCount:  successReq,
		ErrorCount:    errReq,
		TotalTime:     totalTime,
		MinLatency:    minLatency,
		MaxLatency:    maxLatency,
		AvgLatency:    avgLatency,
	}
}

func GenerateLoadReport(filename string, target string, users int, r LoadResult) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	rps := float64(r.TotalRequests) / r.TotalTime.Seconds()

	f.WriteString(fmt.Sprintf("# 🚀 Performance & Load Test Report\n\n"))
	f.WriteString(fmt.Sprintf("**Target:** `%s`\n", target))
	f.WriteString(fmt.Sprintf("**Simulated Users:** `%d concurrent routines`\n", users))
	f.WriteString(fmt.Sprintf("**Test Duration:** `%v`\n\n", r.TotalTime))

	f.WriteString("## 📊 Results Summary\n\n")
	f.WriteString(fmt.Sprintf("- **Total Requests:** `%d`\n", r.TotalRequests))
	f.WriteString(fmt.Sprintf("- **Successful Responses:** `%d`\n", r.SuccessCount))
	f.WriteString(fmt.Sprintf("- **Failed Responses:** `%d`\n", r.ErrorCount))
	f.WriteString(fmt.Sprintf("- **Requests Per Second (RPS):** `%.2f req/s`\n\n", rps))

	f.WriteString("## ⏱️ Latency Distribution\n\n")
	f.WriteString(fmt.Sprintf("- **Minimum Latency:** `%v`\n", r.MinLatency))
	f.WriteString(fmt.Sprintf("- **Maximum Latency:** `%v`\n", r.MaxLatency))
	f.WriteString(fmt.Sprintf("- **Average Latency:** `%v`\n\n", r.AvgLatency))

	f.WriteString("---\n*Generated by Enterprise Web QA Automation CLI*\n")
	return nil
}
