package loadtester

import (
	"bytes"
	"fmt"
	"math/rand"
	"net/http"
	"os"
	"strings"
	"sync"
	"sync/atomic"
	"time"
)

type LoadResult struct {
	TotalRequests int64
	SuccessCount  int64
	ErrorCount    int64
	TotalTime     time.Duration
	MinLatency    time.Duration
	MaxLatency    time.Duration
	AvgLatency    time.Duration
}

func RunLoadTest(targetURL string, users int, duration time.Duration, method string, bodyJson string) LoadResult {
	var wg sync.WaitGroup
	var totalReq, successReq, errReq int64

	// Channels to communicate latency. Make it buffered to avoid blocking routines.
	latencyCh := make(chan time.Duration, users*1000)

	// Stop channel
	stopCh := make(chan struct{})
	go func() {
		time.Sleep(duration)
		close(stopCh)
	}()

	start := time.Now()

	// Seed PRNG for mutations
	rand.Seed(time.Now().UnixNano())

	for i := 0; i < users; i++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			client := &http.Client{Timeout: 10 * time.Second}
			for {
				select {
				case <-stopCh:
					return
				default:
					// Dynamic Mutation [Phase 2: Advanced Feature]
					currentBody := bodyJson
					if currentBody != "" && strings.Contains(currentBody, "{{RANDOM}}") {
						randomVal := fmt.Sprintf("%d", rand.Intn(9999999))
						currentBody = strings.ReplaceAll(currentBody, "{{RANDOM}}", randomVal)
					}

					var req *http.Request
					var err error

					if currentBody != "" {
						req, err = http.NewRequest(method, targetURL, bytes.NewBuffer([]byte(currentBody)))
						if req != nil {
							req.Header.Set("Content-Type", "application/json")
						}
					} else {
						req, err = http.NewRequest(method, targetURL, nil)
					}

					if err != nil {
						atomic.AddInt64(&errReq, 1)
						continue
					}

					reqStart := time.Now()
					resp, err := client.Do(req)
					latency := time.Since(reqStart)

					atomic.AddInt64(&totalReq, 1)

					if err != nil || resp.StatusCode >= 400 {
						atomic.AddInt64(&errReq, 1)
					} else {
						atomic.AddInt64(&successReq, 1)
					}

					if resp != nil && resp.Body != nil {
						resp.Body.Close()
					}

					// Safely send to channel without blocking if highly congested
					select {
					case latencyCh <- latency:
					default:
					}
				}
			}
		}()
	}

	wg.Wait()
	close(latencyCh)
	totalTime := time.Since(start)

	var minLatency time.Duration = 999 * time.Hour
	var maxLatency time.Duration = 0
	var totalLatency time.Duration = 0
	var recordedCount int64 = 0

	for l := range latencyCh {
		if l < minLatency {
			minLatency = l
		}
		if l > maxLatency {
			maxLatency = l
		}
		totalLatency += l
		recordedCount++
	}

	var avgLatency time.Duration
	if recordedCount > 0 {
		avgLatency = time.Duration(int64(totalLatency) / recordedCount)
	} else {
		minLatency = 0
	}

	return LoadResult{
		TotalRequests: totalReq,
		SuccessCount:  successReq,
		ErrorCount:    errReq,
		TotalTime:     totalTime,
		MinLatency:    minLatency,
		MaxLatency:    maxLatency,
		AvgLatency:    avgLatency,
	}
}

func GenerateLoadReport(filename string, target string, users int, r LoadResult) error {
	f, err := os.Create(filename)
	if err != nil {
		return err
	}
	defer f.Close()

	rps := float64(r.TotalRequests) / r.TotalTime.Seconds()

	f.WriteString(fmt.Sprintf("# 🚀 Performance & Load Test Report\n\n"))
	f.WriteString(fmt.Sprintf("**Target:** `%s`\n", target))
	f.WriteString(fmt.Sprintf("**Simulated Users:** `%d concurrent routines`\n", users))
	f.WriteString(fmt.Sprintf("**Test Duration:** `%v`\n\n", r.TotalTime))

	f.WriteString("## 📊 Results Summary\n\n")
	f.WriteString(fmt.Sprintf("- **Total Requests:** `%d`\n", r.TotalRequests))
	f.WriteString(fmt.Sprintf("- **Successful Responses:** `%d`\n", r.SuccessCount))
	f.WriteString(fmt.Sprintf("- **Failed Responses:** `%d`\n", r.ErrorCount))
	f.WriteString(fmt.Sprintf("- **Requests Per Second (RPS):** `%.2f req/s`\n\n", rps))

	f.WriteString("## ⏱️ Latency Distribution\n\n")
	f.WriteString(fmt.Sprintf("- **Minimum Latency:** `%v`\n", r.MinLatency))
	f.WriteString(fmt.Sprintf("- **Maximum Latency:** `%v`\n", r.MaxLatency))
	f.WriteString(fmt.Sprintf("- **Average Latency:** `%v`\n\n", r.AvgLatency))

	f.WriteString("---\n*Generated by Enterprise Web QA Automation CLI*\n")
	return nil
}
